dataset:
  train:
    name: mixed
    prob_ls: [0.4, 0.3, 0.3]
    dataset_list: 
    - name: ceiling_fan
      disp_name: ceiling_fan_train
      dir: fan_separate.tar
      filenames: data_split/fan_separate/fan_separate_split_all_train.txt

    - name: fnaf_fan
      disp_name: fnaf_fan_train
      dir: fnaf_fan_separate.tar
      filenames: data_split/fnaf_fan_separate/fnaf_fan_separate_split_all_train.txt
    
    - name: plane
      disp_name: plane_train
      dir: plane_separate_simple.tar
      filenames: data_split/plane_separate_simple/plane_separate_split_all_train.txt